config/routes.rb
Rails.application.routes.draw do

  get 'category' => 'businesses#category'

  resources :services

  get '/services/:id/payment' => 'services#payment'

  get '/services/:id/confirm' => 'services#confirm'

  resources :businesses

  root 'static_pages#home'

  get 'login' => 'session#show'

end

app/models/business.rb
class Business < ActiveRecord::Base

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence:true, length: {maximum: 50}
	validates :email, presence:true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  validates :password, presence:true
end

app/models/quote_type.rb
class QuoteType < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :service_category
  belongs_to :quote_type
end

app/models/service_category.rb
class ServiceCategory < ActiveRecord::Base
  #attr_reader :id, :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionHelper
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @services = Service.all
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        flash[:warning] = "Look how the header is different! The background is according to the service nature and there is a different logo!<br>
        The application aims to be a lot more customizable, reflecting the uniqueness of each business. Thus, it will appear to be a different website for each business."

        flash[:success] = "Congrats! You got your business up and running. Now it's time to register your services"

        log_in @business

        format.html { redirect_to @business }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def category
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :email, :password, :telephone, :logo)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :payment, :confirm]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    set_business

    respond_to do |format|
      if @service.save
        flash[:success] = "Congrats! your service is registered."

        format.html { redirect_to business_path(current_business) }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment
  end

  def confirm
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    def set_business
      @service.business_id = session[:business_id] || 1
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :service_category_id, :availability, :quote_type_id, :base_price)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    business = Business.find_by(id: 1)
    log_in business
    redirect_to business
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def show
    flash[:success] = "The Login and Sign-up function are not implemented yet. You are now signed-up as a default business."

    redirect_to '/businesses/1/'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper

  def default_business
    business = Business.find_by(id: session[:business_id]) || Business.find_by(id: 1)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def log_in(business)
    session[:business_id] = business.id
  end

  def current_business
    @current_business = Business.find_by(id: session[:business_id])
  end

  def logged_in?
    !current_business.nil?
  end

  def log_out
    session.delete(:business_id)
    @current_business = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/businesses/_form.html.erb
<h3>Fill with details about your business</h3>

  <%= form_for(@business, html: {class: 'form-horizontal'}) do |f| %>
    <% if @business.errors.any? %>
      <div id="error_explanation">
        <h2>Oops! Try again fixing the following errors:</h2>

        <ul>
        <% @business.errors.full_messages.each do |message| %>
          <li class="alert alert-danger"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, nil, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :name %>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-4">Motto</label>
      <div class="col-sm-8">
        <input type="text"></input>
        <small>Haven't got a nice phrase to put here?You can leave it for later!</small>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :description, 'Description of your company', class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_area :description, cols: '50', rows: '7' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.email_field :email %>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :telephone, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :telephone %>
      </div>

    </div>
    <div class="form-group">
      <%= f.label :logo, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <input type="button" disabled="true" class="btn btn-primary" value="Pick an image"></input>
        <small>Sorry, the image picker is not available yet. Don't worry, we're gonna set a nice default logo for you.</small>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :password, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.password_field :password %>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>

    </div>

    <div class="form-group">

      <label class="control-label col-sm-4">Password confirmation</label>

      <div class="col-sm-8">
        <input type="password"></input>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>

    </div>

    <div class="col-sm-offset-2">
      <%= f.submit class:'btn btn-success' %>
    </div>
  <% end %>

app/views/businesses/_form_individual.html.erb
<div class="alert alert-success">
  As an individual worker or freelancer, the user has different fields to fill in.<br>
  Here the form is quite simplistic, but the application aims to develop a dynamic and easy registering.
</div>
<h3>Fill with your personal details</h3>

  <%= form_for(@business, html: {class: 'form-horizontal'}) do |f| %>
    <% if @business.errors.any? %>
      <div id="error_explanation">
        <h2>Oops! Try again fixing the following errors:</h2>

        <ul>
        <% @business.errors.full_messages.each do |message| %>
          <li class="alert alert-danger"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, nil, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :name %>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-4">Your motto</label>
      <div class="col-sm-8">
        <input type="text"></input>
        <small>Haven't got a nice phrase to put here?You can leave it for later!</small>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :description, 'A brief description about you', class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_area :description, cols: '50', rows: '7' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.email_field :email %>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :telephone, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :telephone %>
      </div>

    </div>
    <div class="form-group">
      <%= f.label :logo, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <input type="button" disabled="true" class="btn btn-primary" value="Pick an image"></input>
        <small>Sorry, the image picker is not available yet. Don't worry, we're gonna set a nice default logo for you.</small>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :password, class: 'control-label col-sm-4' %>
      <div class="col-sm-8">
        <%= f.password_field :password %>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>

    </div>

    <div class="form-group">

      <label class="control-label col-sm-4">Password confirmation</label>

      <div class="col-sm-8">
        <input type="password"></input>
        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
      </div>

    </div>

    <div class="col-sm-offset-2">
      <%= f.submit class:'btn btn-success' %>
    </div>
  <% end %>

app/views/businesses/category.html.erb
<div class="container">

  <h2 class="text-primary">Select the category</h2>

  <div class="row">

    <div class="col-sm-6">
      <a href="/businesses/new?category=business" class="btn btn-primary">Small Business</a>
    </div>

    <div class="col-sm-6">
      <a href="/businesses/new?category=individual" class="btn btn-primary">Individual Worker / Free Lancer</a>
    </div>
  </div>

</div>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Businesses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Email</th>
      <th>Password</th>
      <th>Telephone</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.description %></td>
        <td><%= business.email %></td>
        <td><%= business.password %></td>
        <td><%= business.telephone %></td>
        <td><%= business.logo %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<div class="container">
  <h1 class="orange">Engage in the e-commerce world now!</h1>

  <% if params[:category] == 'business'  %>
    <%= render 'form' %>
  <% else %>
    <%= render 'form_individual' %>
  <% end %>

  <%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/show.html.erb
<div class="alert alert-warning">
  Some images used for listing the services were taken under the license <a href="http://pixabay.com/pt/service/terms/#download_terms">CC0 Public Domain</a>
</div>

<header class="navbar-fixed-top" id="business-header">
  <%= link_to 'home', root_path, class: 'pull-left' %>
  <div class="container">
    <div class="col-xs-4 logo">
      <%= @business.name %>
    </div>

    <div class="col-xs-4">
      <label>share your e-commerce to the world!</label><br>

      <%= render 'layouts/socialmedia' %>

    </div>
    <div class="col-xs-4">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Edit Profile', edit_business_path(@business) %>
          </li>
          <li>
            <%= link_to "Log out", root_path, id:'logout' %>
          </li>
          <li>
            <%= link_to "New Service", new_service_path, class: 'btn btn-success' %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">

    <div class="col-sm-6" id="business-details">
      <h1 class="motto">Experienced and thorough cleaners! <small class="text-danger">(Dynamic motto will be placed here)</small></h1>
      <p>
        <%= @business.description %>
      </p>
    </div>

    <div class="col-sm-6">
      <h2>Get in touch, <small>send us a message</small></h2>

      <form>
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="contact-name" placeholder="Enter your name">
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="contact-email" placeholder="Enter your email">
        </div>
        <div class="form-group">
          <label for="subject">Subject</label>
          <input type="text" class="form-control" id="contact-subject" placeholder="Enter the subject">
        </div>
        <%= button_to 'Submit', :back, action: 'get', class: 'btn btn-primary' %>
      </form>
    </div>

  </div>

  <div class="row">
    <h2>Check out our list of services</h2>

    <%= render 'services/list' %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="container-fluid">
  <span>WARNING: this website is a prototype and all the functionalities shown are fictitious.</span>
</div>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top" id="main-header">

  <div class="container">
    <div class="col-xs-4 logo">
        <%= link_to "Service Finder", root_path %>
    </div>
    <div class="col-xs-8">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Log in", '/login', id:'login' %>
          </li>
          <li>
            <%= link_to "Sign up", '/login', id:'signup' %>
          </li>
          <li>
            <a href="/category" class="btn btn-success">Register your business</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_socialmedia.html.erb
<a class="btn btn-sm btn-social-icon btn-twitter">
  <i class="fa fa-twitter"></i>
</a>
<a class="btn btn-sm btn-social-icon btn-facebook">
  <i class="fa fa-facebook"></i>
</a>
<a class="btn btn-sm btn-social-icon btn-google-plus">
  <i class="fa fa-google-plus"></i>
</a>
<a class="btn btn-sm btn-social-icon btn-linkedin">
  <i class="fa fa-linkedin"></i>
</a>
<a class="btn btn-sm btn-social-icon btn-pinterest">
  <i class="fa fa-pinterest"></i>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServicePlatform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <% flash.each do |message_type, message | %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :service_category %>
    <br>

    <select name="service[service_category_id]">
      <% ServiceCategory.all.each do |cat| %>
          <option value="<%= cat.id %>"><%= cat.category %></option>
      <% end %>
    </select>
    <small class="text text-danger">Some services need to have further negotiation, thus they will have a 'send request' button rather than a 'confirm book' button.</small>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </div>
  <div class="field">
    <%= f.label :quote_type_id %><br>

    <select name="service[quote_type_id]">
        <option value="1">Direct book and payment</option>
        <option value="2">Negotiation needed</option>
    </select>

  </div>
  <div class="field">
    <%= f.label :base_price %>
    <br>
    <%= f.text_field :base_price %>
    <small class="text text-danger">We always ask for a fixed baseline price. One of the aims of the application is to ease the process of hiring services.</small>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/services/_list.html.erb
<div class="row">

  <% @services.each do |service| %>

    <div class="col-sm-3 col-md-3">
      <div class="thumbnail service-block">
        <%= image_tag 'cleaner-service.jpg' %>
        <div class="caption">
          <h3 class="service-name"><%= link_to service.name, service_path(service) %></h3>

          <p class="service-description"><%= service.description %></p>

          <p class="bg-success">
            Available: all week-days
          </p>

          <div>
            rate: <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star"></span>
          </div>

          <div>
            reviews: 98
          </div>

          <hr>

          <p>
            <%= button_to 'Hire', service_path(1), method: :get, class: 'btn btn-success pull-left' %>
            <%= button_to 'Details', service_path(1), method: :get, class: 'btn btn-default' %>
          </p>

          <div class="pull-right bg-primary">
            <span>Price : <%= service.base_price %> p/h</span>
          </div>
        </div>
      </div>
    </div>

  <% end %>

</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Base price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.base_price %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/confirm.html.erb
<div class="container">
  <h1>Confirmation</h1>

  <% if @service.id.even? %>

    <h2 class="text-warning">Oops! It seems like your payment was declined.
      <a href="/services/<%= @service.id %>/payment">Try again</a>!
    </h2>

  <% else %>
    <h2 class="text-success">Congrats! The service is booked and confirmed.<small>here is your <a href="#">receipt</a></small></h2>

  <% end  %>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div id="search" class="row">

      <form class="form-inline">
        <div class="form-group">
          <div class="dropdown" id="dropdown-categories">

            <button id="dropdown-categories" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expended="false">

              <span class="glyphicon glyphicon-list"></span>
            </button>

            <ul class="dropdown-menu" role="menu" aria-labelledbye="dropdown-categories">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Home & Office</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">IT Services</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Gardening</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Health & Beauty</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Sport and Fitness</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Marketing</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Restaurants</a></li>
            </ul>
          </div>

          <div class="input-group">

            <label class="sr-only">Search: </label>
            <input id="search-text" type="text" class="form-control" placeholder="What service do you need?"></input>

            <%= link_to 'Search', services_path, class: 'btn btn-primary' %>
          </div>
        </div>

      </form>
  </div>

  <%= render 'services/list' %>
</div>



<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<div class="container">

  <h1>Register your service</h1>

  <%= render 'form' %>

  <%= link_to 'Back', services_path %>
</div>

app/views/services/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="thumbnail service-block">

        <%= image_tag 'cleaner-service.jpg' %>

        <div class="caption">
          <h3 class="service-name"><%= @service.name %></h3>

          <p class="service-description"><%= @service.description %></p>

          <p>
            Available: all week-days
          </p>

          <div class="col-sm-7">
            rate: <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star text-primary"></span>
            <span class="glyphicon glyphicon-star"></span>
          </div>

          <div class="col-sm-5">
            reviews: 98
          </div>

          <p>
            .
          </p>
          <div class="pull-right bg-primary">
            <span>Price : <%= @service.base_price %> p/h</span>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-6">
      <h3>Want to hire this service?<br>
        <small class="text-success">Just fill in this form and proceed to the payment.</small>
      </h3>

      <form class="form-horizontal" action="/services/<%= @service.id %>/payment" method="get" >

        <% if !@service.id.even? %>

        <div class="form-group">
          <label class="col-sm-4 control-label" for="name">Quantity</label>

          <div class="col-sm-2">
            <input type="text" class="form-control" id="service-quantity" placeholder="1">
          </div>
        </div>

        <% end %>
        
        <div class="form-group">
          <label class="col-sm-4 control-label" for="email">Date(s)</label>

          <div class="col-sm-8">
            <input type="date" class="form-control" id="contact-email">
            <small class="text-danger">This field will contain as many dates as it is specified in the 'quantity field'.</small>

          </div>


        </div>
        <% if @service.id.even? %>
        <div class="form-group">
          <label class="col-sm-4 control-label" for="subject">Description</label>

          <div class="col-sm-8">
            <textarea rows="5" class="form-control" id="contact-subject"></textarea>
          </div>
        </div>

        <% end %>
        <div class="form-group">
          <div class="col-sm-offset-5">
            <%= submit_tag 'Proceed to payment', class: 'btn btn-primary' %>
          </div>
        </div>
      </form>
    </div>

  </div>

  <%= link_to 'Edit', edit_service_path(@service) %> |
  <%= link_to 'Back', services_path %>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div id="search" class="row">

      <form class="form-inline" action="/services/">
        <h2>Find the service you need and hire it straight away</h2>
        <div class="form-group">
          <div class="dropdown" id="dropdown-categories">

            <button id="dropdown-categories" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expended="false">
              <span class="glyphicon glyphicon-list"></span>
            </button>

            <ul class="dropdown-menu" role="menu" aria-labelledbye="dropdown-categories">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Home & Office</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">IT Services</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Gardening</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Health & Beauty</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Sport and Fitness</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Marketing</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Restaurants</a></li>
            </ul>
          </div>

          <div class="input-group">

            <label class="sr-only">Search: </label>
            <input id="search-text" type="text" class="form-control" placeholder="What service do you need?"></input>

            <%= button_to 'Search', services_path, class: 'btn btn-primary' %>
          </div>
        </div>

      </form>
  </div>

  <div class="row">
    <h2 class="orange text-center">See how is easy to register your business</h2>
    <hr />
    <div class="col-sm-6">
      <h2><span class="text-primary">Step 1: </span><small>Register your business</small></h2>

      <h2><span class="text-primary">Step 2: </span><small>Register your services</small></h2>

      <h2><span class="text-primary">Step 3: </span><small>Share your page</small></h2>

      <h3 class="text-success">Your are done!</h3>
    </div>

    <div class="col-sm-6">
      <%= image_tag "how-works.png", id:'how-works' %>

    </div>

  </div>

</div>